@startuml diagrama3

    actor Aitor
    actor Olga
    database DataBase #red

    Aitor -> DataBase: Saludas
    Aitor -> Olga : Saluda
    note right : cortesia
    Olga -> Olga : ¿me está saludando?
    Aitor <-- Olga : Hola

@enduml