@startuml diagrama4

    == Comienzo ==

    Elemento -[#0066ff]x Elemento2
    Elemento2 -[#0066ff]-\ Elemento
    Elemento2 <-[#0066ff]> Elemento

    == Final ==

    Elemento -[#0066ff]>O Elemento2

@enduml